name: Automação de vagas

on:
  workflow_dispatch:

jobs:
  teste-automacao:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Executar Python
        run: |
          python main.py
